use:
  default_locale: ''
  autocomplete: ''
  favicon_resolver: ''

server:
  port: 8080
  bind_address: '0.0.0.0'
  secret_key: 'perplexio-internal-searxng-key'
  limiter: false
  public_instance: false

search:
  safe_search: 0
  autocomplete: ''
  default_lang: 'en-US'
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: bing
    engine: bing
    shortcut: bi
    disabled: false

  - name: brave
    engine: brave
    shortcut: br
    disabled: false

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false

  - name: wikidata
    engine: wikidata
    shortcut: wd
    disabled: true

  - name: reddit
    engine: reddit
    shortcut: re
    disabled: false
    categories: social media

  - name: twitter
    engine: twitter
    shortcut: tw
    disabled: false
    categories: social media

outgoing:
  request_timeout: 10.0
  max_request_timeout: 15.0
  useragent_suffix: ''
  pool_connections: 100
  pool_maxsize: 20
